---
title: "MMA & Lung Cancer Analysis"
author: "Rachel Heise, MS"
pi: "Yiwey Shieh, MD"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  wcmtheme::wcm_html: 
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(survival)
library(tidyverse)
library(gtsummary)

load("/Volumes/Shieh-share$/MMA_Cancer/output/matched_data_3.RData")
load("/Volumes/Shieh-share$/MMA_Cancer/output/matched_data_4.RData")

```

## Conditional Logistic Regression

This is a 1:3 matched case-control study, assessing if there is an association between MMA and lung cancer. 

Units of lab data:

  - MMA: nmol/L
  - B12: pg/mL
  - Creatinine: mg/dL

```{r}
# take the log of MMA and standardize it to calculate the standardized OR

matched_data_3 <- matched_data_3 %>% 
  mutate(log_MMA = log(MMA),
         log_MMA_standardized = log(MMA)/sd(log(MMA)))

# matched_data_3 %>% 
#   ggplot(aes(x = log(B12))) +
#   geom_histogram(bins = 15)

model <- clogit(cancer ~ log_MMA_standardized + age + log(B12) + log(CREATININE) + strata(subclass),
                data = matched_data_3, id = subclass)

model %>% 
  tbl_regression(exp = T,
                 estimate_fun = purrr::partial(style_ratio, digits = 4)) %>%
  bold_p()

model2 <- clogit(cancer ~ MMA + age + B12 + CREATININE + strata(subclass),
                 data = matched_data_3, id = subclass)

model %>% 
  tbl_regression(exp = T,
                 estimate_fun = purrr::partial(style_ratio, digits = 4)) %>%
  bold_p()
```

<br>

## Compare Log-transformed and Untransformed models

```{r}
library(AICcmodavg)

models_list <- list(model, model2)
#specify model names
mod.names <- c('log-transformed', 'untransformed')

#calculate AIC of each model
aictab(cand.set = models_list, modnames = mod.names)
```


```{r, eval=FALSE, include = FALSE}
model <- clogit(cancer ~ log_MMA + B12 + strata(subclass),
                data = matched_data_3, id = subclass)
# summary(model)

model %>% 
  tbl_regression(exp = T,
                 estimate_fun = purrr::partial(style_ratio, digits = 4)) %>%
  bold_p()
```

## Check model assumptions

```{r, message=FALSE, echo = FALSE}
model_untransformed <- glm(cancer ~ MMA + B12 + CREATININE + age,
                           data = matched_data_3, family = binomial)

probabilities <- predict(model_untransformed, type = "response")
predicted.classes <- ifelse(probabilities > 0.5, "pos", "neg")
head(predicted.classes)

predictors <- c("MMA", "B12", "CREATININE", "age")
data_untransformed <- matched_data_3 %>%
  select(MMA, B12, CREATININE, age) %>% 
  mutate(logit = log(probabilities/(1-probabilities))) %>%
  gather(key = "predictors", value = "predictor.value", -logit)

ggplot(data_untransformed, aes(logit, predictor.value))+
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "loess") + 
  theme_bw() + 
  facet_wrap(~predictors, scales = "free_y") +
  labs(title = "Untransformed model")
```

```{r, message=FALSE, echo = FALSE}
data_transformed <- matched_data_3 %>% 
  mutate(log_B12 = log(B12),
         log_CREATININE = log(CREATININE))

model_transformed <- glm(cancer ~ log_MMA + log_B12 + log_CREATININE + age,
                             data = data_transformed, family = binomial)

probabilities <- predict(model_transformed, type = "response")
predicted.classes <- ifelse(probabilities > 0.5, "pos", "neg")
# head(predicted.classes)

predictors <- c("log_MMA", "log_B12", "log_CREATININE", "age")
data_transformed <- data_transformed %>%
  select(log_MMA, log_B12, log_CREATININE, age) %>% 
  mutate(logit = log(probabilities/(1-probabilities))) %>%
  gather(key = "predictors", value = "predictor.value", -logit)

ggplot(data_transformed, aes(logit, predictor.value))+
  geom_point(size = 0.5, alpha = 0.5) +
  geom_smooth(method = "loess") + 
  theme_bw() + 
  facet_wrap(~predictors, scales = "free_y") +
  labs(title = "Log-transformed model")
```


```{r, eval=FALSE, include=FALSE}
matched_data_3_cases <- matched_data_3 %>% 
  filter(cancer == 1)

matched_data_3_controls <- matched_data_3 %>% 
  filter(cancer == 0)

matched_data_3 %>% 
  ggplot(aes(x = CREATININE, fill = as.factor(cancer))) +
  geom_density(alpha = 0.5)

# try to avoid sparse data problem by filtering on CREATININE < 1.01 which is the max value of CREATININE
# in the cases group

matched_data_3_creatinine <- matched_data_3 %>% 
  filter(CREATININE <= 1.01)

model2 <- clogit(cancer ~ MMA + age + B12 + CREATININE + strata(subclass),
                data = matched_data_3_creatinine, id = subclass)
summary(model2)

model2 %>% 
  tbl_regression(exp = T,
                 estimate_fun = purrr::partial(style_ratio, digits = 4)) %>%
  bold_p()

```

```{r, eval=FALSE, include=FALSE}
# try analysis with 1:4 data

model4 <- clogit(cancer ~ MMA + age + B12 + CREATININE + strata(subclass),
                data = matched_data_4, id = subclass)
# summary(model)

model4 %>% 
  tbl_regression(exp = T,
                 estimate_fun = purrr::partial(style_ratio, digits = 4)) %>%
  bold_p()
```



