---
title: "NHANES MMA Data"
author: "Rachel Heise, MS"
pi: "Yiwey Shieh, MD"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  wcmtheme::wcm_html: 
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(lubridate)
library(gtsummary)
library(haven)
library(labelled)
library(rstatix) #identify outliers

set_gtsummary_theme(theme_gtsummary_compact())
theme_set(theme_minimal())

load(here::here("./output/NHANES_dat.RData"))

# remove patients without complete MMA, B12, and creatinine data
nhanes_dat <- nhanes_dat %>% 
  filter(complete_data == 1)
```

## Demographics

```{r}
nhanes_dat %>% 
  select(gender, age, age_cat, race_ethnicity, year, B12, CREATININE, MMA, complete_data) %>% 
  tbl_summary(label = list(complete_data ~ "Patients with complete data (B12, creatinine, MMA)",
                           age ~ "Age",
                           age_cat ~ "Age (categorical)",
                           year ~ "NHANES year",
                           race_ethnicity ~ "Race/ethnicity")) %>% 
  bold_labels()
```

## Lab results by age category

### MMA

```{r, fig.width=5, fig.height=4}
nhanes_dat %>% 
  ggplot(aes(x = age_cat, y = log(MMA))) +
  geom_boxplot() +
  labs(x = "Age category")
```

```{r, fig.width=5, fig.height=4}
nhanes_dat %>% 
  filter(B12 > 300, CREATININE < 1.3) %>% 
  ggplot(aes(x = age_cat, y = MMA)) +
  geom_boxplot() +
  labs(x = "Age category",
       title = "MMA for participants with B12 > 300 and \n serum creatinine < 1.3")
```

```{r, fig.width=5, fig.height=4}
nhanes_dat %>% 
  filter(B12 > 300, CREATININE < 1.3) %>% 
  ggplot(aes(x = age_cat, y = log(MMA))) +
  geom_boxplot() +
  labs(x = "Age category",
       title = "log(MMA) for participants with B12 > 300 and \n serum creatinine < 1.3")
```

```{r, fig.width=5, fig.height=4, message=FALSE}
nhanes_dat %>% 
  filter(B12 > 300, CREATININE < 1.3) %>% 
  ggplot(aes(x = log(MMA))) +
  geom_histogram() +
  labs(title = "log(MMA) for participants with B12 > 300 and \n serum creatinine < 1.3")
```

<br>

### B12

```{r, fig.width=5, fig.height=4}
nhanes_dat %>% 
  ggplot(aes(x = age_cat, y = log(B12))) +
  geom_boxplot() +
  labs(x = "Age category",
       y = "log(B12) (pg/mL)")
```

### Creatinine
<br>

```{r, fig.width=5, fig.height=4}
nhanes_dat %>% 
  ggplot(aes(x = age_cat, y = log(CREATININE))) +
  geom_boxplot() +
  labs(x = "Age category", y = "log(Serum Creatinine) (mg/dL)")
```

```{r, eval=FALSE}
# try continuous age (scatterplot)
nhanes_dat %>% 
  ggplot(aes(x = age, y = CREATININE)) +
  geom_point()
```


## Extreme Outliers

Extreme outliers are defined as values above $Q3 + 3 \cdot IQR$, or below $Q1 - 3 \cdot IQR$.

```{r, message = FALSE}
mma_outliers <- identify_outliers(nhanes_dat, variable = "MMA") %>% 
  filter(is.extreme == TRUE)
creatinine_outliers <- identify_outliers(nhanes_dat, variable = "CREATININE") %>% 
  filter(is.extreme == TRUE)
b12_outliers <- identify_outliers(nhanes_dat, variable = "B12") %>% 
  filter(is.extreme == TRUE)

nhanes_dat %>% 
  mutate(`MMA extreme outlier` = if_else(SEQN %in% mma_outliers$SEQN, 1, 0),
         `B12 extreme outlier` = if_else(SEQN %in% b12_outliers$SEQN, 1, 0),
         `Creatinine extreme outlier` = if_else(SEQN %in% creatinine_outliers$SEQN, 1, 0)) %>% 
  select(contains("outlier")) %>% 
  tbl_summary() %>% 
  bold_labels()
```

